apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-app-02-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data-app-02-old" 
