apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-app-02-pvc
  namespace: go-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: go-app-02-pv
