apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-app-01-pvc-v2
  namespace: go-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: go-app-01-pv-v2
